[transport-udp-provider]
type=transport
protocol=udp
bind=0.0.0.0:50605

[provider-reg]
type=registration
transport=transport-udp-provider
outbound_auth=provider-auth
retry_interval=60
expiration=300
auth_rejection_permanent=yes
contact_user=SIP_USER
server_uri=sip:SIP_SERVER_ADDRESS:5060
client_uri=sip:SIP_USER@SIP_SERVER_ADDRES:5060

[provider-auth]
type=auth
auth_type=userpass
username=SIP_USER
password=CLIENT_PASS

[provider-endpoint]
type=endpoint
transport=transport-udp-provider
context=from-provider
disallow=all
allow=alaw,ulaw
outbound_auth=provider-auth
aors=provider-aor
from_domain=SIP_SERVER_ADDRES
from_user=SIP_USER
sdp_owner=SIP_USER
direct_media=no
ice_support=no
send_rpid=yes
rtp_symmetric=yes
force_rport=yes
timers=no

[provider-aor]
type=aor
contact=sip:SIP_SERVER_ADDRES:5060

[provider-identify]
type=identify
endpoint=provider-endpoint
match=SIP_SERVER_ADDRES